# Supplementary material {#anexo}

This section presents the supplementary material for this study. 

```{r}
#| label: source2
#| echo: false
#| results: false
#| message: false
#| warning: false
#| include: false

library(here)
library(cobalt)
library(ggplot2)
library(cowplot)

source(here("processing/prod_analysis_multinom.R"))

table_format <- if (knitr::is_html_output()) {
   #conditional instructions for kable
   "html" #if html set "html" in format
 } else if (knitr::is_latex_output()) {
   "latex"#if latex set "latex" in format
 }

```

## Descriptive statistics

```{r}
#| label: tbl-summary1
#| tbl-cap: "Descriptive statistics for all variables."
#| tbl-cap-location: top
#| results: asis
#| echo: false

library(summarytools)
t1 <- db %>% 
  select(just_pension_f, 
         estrato_orig, 
         estrato_ocupa, 
         educ_orig_f,
         hogar_bip_f, 
         nacionalidad_f, 
         sexo_f,
         m0_edad_f, 
         etnia_f, 
         merit_i,
         wave

)

t1 <- t1 %>% 
  mutate(
    just_pension_f = factor(just_pension_f, levels = c(0,1), labels = c("Disagree", "Agree")),
    hogar_bip_f  = factor(hogar_bip_f, levels = c(0,1), labels = c("No co-residence", "Co-residence")),
    #nacionalidad_f = if_else(nacionalidad_f == 0, 1, 0),
    nacionalidad_f  = factor(nacionalidad_f, levels = c(0,1), labels = c("Non-Chilean", "Chilean")),
    #sexo_f = if_else(sexo_f == 1, 0, 1),
    sexo_f  = factor(sexo_f, levels = c(0,1), labels = c("Male", "Female")),
    etnia_f = factor(etnia_f, levels = c(0,1), labels = c("Non-indigenous", "Indigenous"))
  )

t1$just_pension_f <- sjlabelled::set_label(t1$just_pension_f, "Preference for pension commodification")
t1$educ_orig_f <- sjlabelled::set_label(t1$educ_orig_f, "Parental education")
t1$hogar_bip_f <- sjlabelled::set_label(t1$hogar_bip_f, "Co-residence with both parents at age 15")
t1$nacionalidad_f <- sjlabelled::set_label(t1$nacionalidad_f, "Nacionality")
t1$sexo_f <- sjlabelled::set_label(t1$sexo_f, "Sex")
t1$m0_edad_f <- sjlabelled::set_label(t1$m0_edad_f, "Age (in years)")
t1$etnia_f <- sjlabelled::set_label(t1$etnia_f, "Indigenous ethnicity")
t1$merit_i <- sjlabelled::set_label(t1$merit_i, "Meritocracy perception")
t1$wave <- sjlabelled::set_label(t1$wave, "Wave")

df<-dfSummary(t1,
               plain.ascii = FALSE,
               style = "multiline",
               tmp.img.dir = "/tmp",
               graph.magnif = 0.75,
               headings = F,  # encabezado
               varnumbers = F, # num variable
               labels.col = T, # etiquetas
               na.col = F,    # missing
               graph.col = F, # plot
               valid.col = T, # n valido
               col.widths = c(30,10,10,10))

df$Variable <- NULL # delete variable column

print(df)

```

## Balance evaluation

```{r}
#| label: fig-balance
#| fig-cap: "Balance SMD — Mobility treatment (ATT)"
#| fig-cap-location: bottom
#| echo: false
#| results: asis
#| warning: false
#| out-width: '90%'
#| fig-asp: 0.9


p1 <- cobalt::love.plot(W_lm_ll, stats = "m", abs = TRUE, threshold = .10,
                  var.order = "unadjusted", line = TRUE,
                  colors = c("grey70","black")) +
  ggtitle("Low-Middle")

p2 <- cobalt::love.plot(W_lh_ll, stats = "m", abs = TRUE, threshold = .10,
                  var.order = "unadjusted", line = TRUE,
                  colors = c("grey70","black")) +
  ggtitle("Low-High")

p3 <- cobalt::love.plot(W_mh_mm, stats = "m", abs = TRUE, threshold = .10,
                  var.order = "unadjusted", line = TRUE,
                  colors = c("grey70","black")) +
  ggtitle("Middle-High")

p4 <- cobalt::love.plot(W_ml_mm, stats = "m", abs = TRUE, threshold = .10,
                  var.order = "unadjusted", line = TRUE,
                  colors = c("grey70","black")) +
  ggtitle("Middle-Low")

p5 <- cobalt::love.plot(W_hm_hh, stats = "m", abs = TRUE, threshold = .10,
                  var.order = "unadjusted", line = TRUE,
                  colors = c("grey70","black")) +
  ggtitle("High-Middle")

p6 <- cobalt::love.plot(W_hl_hh, stats = "m", abs = TRUE, threshold = .10,
                  var.order = "unadjusted", line = TRUE,
                  colors = c("grey70","black")) +
  ggtitle("High-Low")

cowplot::plot_grid(p1, p2, p3, p4, p5, p6, label_size = 11, ncol = 2, nrow = 3)

```


## Mobility effects models

```{r}
#| label: tbl-complete1
#| tbl-cap: "Effects of intergenerational occupational mobility on preferences for pension commodification, with covariates and wave fixed effects."
#| tbl-cap-location: top
#| results: asis
#| echo: false

ccoef <- list(
  "(Intercept)" = "Intercept",
  "t" = "Mobility treatment",
  edad = "Age (in years)",
  sexo = "Female (Ref. = Male)",
  nac = "Chilean nacionality (Ref. = Non-Chilean)",
  etnia = "Indigenous ethnicity (Ref. = Non-indigenous)",
  hogar = "Co-residence with both parents (Ref. = No co-residence)",
  edu0 = "Parental education",
  ola2018 = "Wave 2018",
  ola2023 = "Wave 2023"
  
)

texreg::texreg(list(mp_lm,
                       mp_lh,
                       mp_mh,
                       mp_ml,
                       mp_hm,
                       mp_hl),
                  custom.model.names = c(
                    "Low-Middle",
                    "Low-High",
                    "Middle-High",
                    "Middle-Low",
                    "High-Middle",
                    "High-Low"
                  ),   caption.above = NULL,
               caption = NULL,
               custom.coef.map = ccoef,
               digits = 2,
               groups = list("Wave (Ref.= 2016)" = 9:10),
               custom.note = "Note: Cells contain regression coefficients with confidence intervals in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.7,
               center = T,
               float.pos = "H!")
```



```{r}
#| label: tbl-complete2
#| tbl-cap: "Effects of intergenerational occupational mobility on preferences for pension commodification."
#| tbl-cap-location: top
#| results: asis
#| echo: false

# Low to middle

mp_lm_2 <- lm_robust(y ~ t,
                     weights = w,
                     se_type = "CR2",
                     clusters = idencuesta,
                     data = data_lm) 

# Low to high

mp_lh_2 <- lm_robust(y ~ t,
                     weights = w,
                     se_type = "CR2",
                     clusters = idencuesta,
                     data = data_lh) 

# Middle to high

mp_mh_2 <- lm_robust(y ~ t,
                     weights = w,
                     se_type = "CR2",
                     clusters = idencuesta,
                     data = data_mh) 


# Middle to low

mp_ml_2 <- lm_robust(y ~ t,
                     weights = w,
                     se_type = "CR2",
                     clusters = idencuesta,
                     data = data_ml) 

# High to middle

mp_hm_2 <- lm_robust(y ~ t,
                     weights = w,
                     se_type = "CR2",
                     clusters = idencuesta,
                     data = data_hm) 

# High to low

mp_hl_2 <- lm_robust(y ~ t,
                     weights = w,
                     se_type = "CR2",
                     clusters = idencuesta,
                     data = data_hl) 

ccoef <- list(
  "(Intercept)" = "Intercept",
  "t" = "Mobility treatment"
)

texreg::texreg(list(mp_lm_2,
                       mp_lh_2,
                       mp_mh_2,
                       mp_ml_2,
                       mp_hm_2,
                       mp_hl_2),
                  custom.model.names = c(
                    "Low-Middle",
                    "Low-High",
                    "Middle-High",
                    "Middle-Low",
                    "High-Middle",
                    "High-Low"
                  ),   caption.above = NULL,
               caption = NULL,
               custom.coef.map = ccoef,
               digits = 2,
               custom.note = "Note: Cells contain regression coefficients with confidence intervals in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.8,
               center = T,
               float.pos = "H!")
```

```{r}
#| label: tbl-complete3
#| tbl-cap: "Interactions effects between intergenerational occupational mobility and perceived meritocracy on preferences for pension commodification, with covariates and wave fixed effects."
#| tbl-cap-location: top
#| results: asis
#| echo: false


ccoef <- list(
  "(Intercept)" = "Intercept",
  "t" = "Mobility treatment",
  "mHigh" = "High meritocracy perception (Ref.= Low)",
  "t:mHigh" = "Mobility treatment x High meritocracy perception (Ref.= Low)"
)

texreg(list(mp_lm_i,
               mp_lh_i,
               mp_mh_i,
               mp_ml_i,
               mp_hm_i,
               mp_hl_i),
          custom.model.names = c(
            "Low-Middle",
            "Low-High",
            "Middle-High",
            "Middle-Low",
            "High-Middle",
            "High-Low"
          ),
          caption.above = NULL,
          caption = NULL,
          custom.coef.map = ccoef,
          digits = 2,
          custom.note = "Note: Cells contain regression coefficients with confidence intervals in parentheses. %stars.",
          leading.zero = T,
          use.packages = F,
          booktabs = F,
          scalebox = 0.7,
          center = T,float.pos = "H!",
          custom.gof.rows = list("Controls"=rep("Yes",6)))

```



```{r}
#| label: tbl-complete4
#| tbl-cap: "Marginal effects of mobility by meritocratic perception (Low vs High Meritocracy)."
#| tbl-cap-location: top
#| results: asis
#| echo: false


df_tab <- df_pension_lab_i %>%
  mutate(
    Trajectory = sub("\\n.*", "", name),
    Merit = term,
    Estimate = round(estimate, 3),
    `Std. Error` = round(std.error, 3),
    `CI Low` = round(conf.low, 3),
    `CI High` = round(conf.high, 3),
  ) %>%
  select(Trajectory, Merit, Estimate, `Std. Error`, `CI Low`, `CI High`)


kableExtra::kable(df_tab,
      format = table_format,
      caption = NULL,
      align = "lcccccc") %>%
kableExtra::kable_classic(full_width = F, html_font = "Cambria")
```


{{< pagebreak >}}

## Robustness check and sensitivity analysis

```{r}
#| label: tbl-robus1
#| tbl-cap: "Effects of intergenerational occupational mobility on preferences for pension commodification coded as 3-5 vs. 1-2, with covariates and wave fixed effects."
#| tbl-cap-location: top
#| results: asis
#| echo: false

ccoef <- list(
  "(Intercept)" = "Intercept",
  "t" = "Mobility treatment",
  edad = "Age (in years)",
  sexo = "Female (Ref. = Male)",
  nac = "Chilean nacionality (Ref. = Non-Chilean)",
  etnia = "Indigenous ethnicity (Ref. = Non-indigenous)",
  hogar = "Co-residence with both parents (Ref. = No co-residence)",
  edu0 = "Parental education",
  ola2018 = "Wave 2018",
  ola2023 = "Wave 2023"
  
)

texreg::texreg(list(mp_lm_r_i,
                       mp_lh_r_i,
                       mp_mh_r_i,
                       mp_ml_r_i,
                       mp_hm_r_i,
                       mp_hl_r_i),
                  custom.model.names = c(
                    "Low-Middle",
                    "Low-High",
                    "Middle-High",
                    "Middle-Low",
                    "High-Middle",
                    "High-Low"
                  ),   caption.above = NULL,
               caption = NULL,
               custom.coef.map = ccoef,
               digits = 2,
               groups = list("Wave (Ref.= 2016)" = 9:10),
               custom.note = "Note: Cells contain regression coefficients with confidence intervals in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.7,
               center = T,
               float.pos = "H!")
```

```{r}
#| label: tbl-robus2
#| tbl-cap: "Effects of intergenerational occupational mobility on preferences for pension commodification excluding intermediate category, with covariates and wave fixed effects."
#| tbl-cap-location: top
#| results: asis
#| echo: false

ccoef <- list(
  "(Intercept)" = "Intercept",
  "t" = "Mobility treatment",
  edad = "Age (in years)",
  sexo = "Female (Ref. = Male)",
  nac = "Chilean nacionality (Ref. = Non-Chilean)",
  etnia = "Indigenous ethnicity (Ref. = Non-indigenous)",
  hogar = "Co-residence with both parents (Ref. = No co-residence)",
  edu0 = "Parental education",
  ola2018 = "Wave 2018",
  ola2023 = "Wave 2023"
  
)

texreg::texreg(list(mp_lm_r_ii,
                       mp_lh_r_ii,
                       mp_mh_r_ii,
                       mp_ml_r_ii,
                       mp_hm_r_ii,
                       mp_hl_r_ii),
                  custom.model.names = c(
                    "Low-Middle",
                    "Low-High",
                    "Middle-High",
                    "Middle-Low",
                    "High-Middle",
                    "High-Low"
                  ),   caption.above = NULL,
               caption = NULL,
               custom.coef.map = ccoef,
               digits = 2,
               groups = list("Wave (Ref.= 2016)" = 9:10),
               custom.note = "Note: Cells contain regression coefficients with confidence intervals in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.7,
               center = T,
               float.pos = "H!")
```

```{r}
#| label: tbl-robus3
#| tbl-cap: "Effects of intergenerational occupational mobility on preferences for pension commodification using the original 5-point likert scale, with covariates and wave fixed effects."
#| tbl-cap-location: top
#| results: asis
#| echo: false

ccoef <- list(
  "(Intercept)" = "Intercept",
  "t" = "Mobility treatment",
  edad = "Age (in years)",
  sexo = "Female (Ref. = Male)",
  nac = "Chilean nacionality (Ref. = Non-Chilean)",
  etnia = "Indigenous ethnicity (Ref. = Non-indigenous)",
  hogar = "Co-residence with both parents (Ref. = No co-residence)",
  edu0 = "Parental education",
  ola2018 = "Wave 2018",
  ola2023 = "Wave 2023"
  
)

texreg::texreg(list(mp_lm_r_iii,
                       mp_lh_r_iii,
                       mp_mh_r_iii,
                       mp_ml_r_iii,
                       mp_hm_r_iii,
                       mp_hl_r_iii),
                  custom.model.names = c(
                    "Low-Middle",
                    "Low-High",
                    "Middle-High",
                    "Middle-Low",
                    "High-Middle",
                    "High-Low"
                  ),   caption.above = NULL,
               caption = NULL,
               custom.coef.map = ccoef,
               digits = 2,
               groups = list("Wave (Ref.= 2016)" = 9:10),
               custom.note = "Note: Cells contain regression coefficients with confidence intervals in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.7,
               center = T,
               float.pos = "H!")
```


```{r}
#| label: tbl-evalues1
#| tbl-cap: "E-values for ATT estimates for Middle-High trajectory (Cinelli & Hazlett, 2020 approximation)"
#| tbl-cap-location: top
#| results: asis
#| echo: false

ovb_minimal_reporting(mh_evalue, format = "latex")
```


```{r}
#| label: tbl-evalues2
#| tbl-cap: "E-values for ATT estimates for High-Middle trajectory (Cinelli & Hazlett, 2020 approximation)"
#| tbl-cap-location: top
#| results: asis
#| echo: false

ovb_minimal_reporting(hm_evalue, format = "latex")
```


```{r}
#| label: tbl-evalues3
#| tbl-cap: "E-values for ATT estimates for High-Low trajectory (Cinelli & Hazlett, 2020 approximation)"
#| tbl-cap-location: top
#| results: asis
#| echo: false

ovb_minimal_reporting(hl_evalue, format = "latex")
```

